#!/bin/bash
#SBATCH --partition=lab-real
#SBATCH --cpus-per-task=56
#SBATCH --gres=gpu:a6000:7                              
#SBATCH --mem=800G                                       
#SBATCH --time=500:00:00                                           
#SBATCH -o /network/scratch/r/roger.creus-castanyer/slurm-%j.out 

# 1. Load your environment
module load anaconda/3

#export CUDA_DEVICE_ORDER=PCI_BUS_ID
#export CUDA_VISIBLE_DEVICES=1,2
#export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
export OMP_NUM_THREADS=2

conda activate /home/mila/r/roger.creus-castanyer/anaconda3/envs/mario

# 4. Launch your job, tell it to save the model in $SLURM_TMPDIR
#    and look for the dataset into $SLURM_TMPDIR

torchrun --standalone --nnodes 1 --nproc_per_node 14 ppo_unet_multigpu.py --self-play True  --pool-size 5 --sparse-reward False --simple-obs False --track --num-envs 28 --num-steps 32 --eval-interval 50 --save-every 25 --device-ids 0 0 1 1 2 2 3 3 4 4 5 5 6 6


# 5. Copy whatever you want to save on $SCRATCH
cp -r $SLURM_TMPDIR/* /network/scratch/r/roger.creus-castanyer/